//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VvvfSimulator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40000")]
        public int RealTime_VVVF_BuffSize {
            get {
                return ((int)(this["RealTime_VVVF_BuffSize"]));
            }
            set {
                this["RealTime_VVVF_BuffSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RealTime_VVVF_WaveForm_Line_Show {
            get {
                return ((bool)(this["RealTime_VVVF_WaveForm_Line_Show"]));
            }
            set {
                this["RealTime_VVVF_WaveForm_Line_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_VVVF_EditAllow {
            get {
                return ((bool)(this["RealTime_VVVF_EditAllow"]));
            }
            set {
                this["RealTime_VVVF_EditAllow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40000")]
        public int RealTime_Train_BuffSize {
            get {
                return ((int)(this["RealTime_Train_BuffSize"]));
            }
            set {
                this["RealTime_Train_BuffSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_Train_EditAllow {
            get {
                return ((bool)(this["RealTime_Train_EditAllow"]));
            }
            set {
                this["RealTime_Train_EditAllow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_Train_WaveForm_Line_Show {
            get {
                return ((bool)(this["RealTime_Train_WaveForm_Line_Show"]));
            }
            set {
                this["RealTime_Train_WaveForm_Line_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_VVVF_Control_Show {
            get {
                return ((bool)(this["RealTime_VVVF_Control_Show"]));
            }
            set {
                this["RealTime_VVVF_Control_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_Train_Control_Show {
            get {
                return ((bool)(this["RealTime_Train_Control_Show"]));
            }
            set {
                this["RealTime_Train_Control_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RealTime_VVVF_Control_Style {
            get {
                return ((int)(this["RealTime_VVVF_Control_Style"]));
            }
            set {
                this["RealTime_VVVF_Control_Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RealTime_Train_Control_Style {
            get {
                return ((int)(this["RealTime_Train_Control_Style"]));
            }
            set {
                this["RealTime_Train_Control_Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RealTime_VVVF_Control_Language {
            get {
                return ((int)(this["RealTime_VVVF_Control_Language"]));
            }
            set {
                this["RealTime_VVVF_Control_Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RealTime_Train_Control_Language {
            get {
                return ((int)(this["RealTime_Train_Control_Language"]));
            }
            set {
                this["RealTime_Train_Control_Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_VVVF_Hexagon_Show {
            get {
                return ((bool)(this["RealTime_VVVF_Hexagon_Show"]));
            }
            set {
                this["RealTime_VVVF_Hexagon_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_Train_Hexagon_Show {
            get {
                return ((bool)(this["RealTime_Train_Hexagon_Show"]));
            }
            set {
                this["RealTime_Train_Hexagon_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RealTime_VVVF_Hexagon_Style {
            get {
                return ((int)(this["RealTime_VVVF_Hexagon_Style"]));
            }
            set {
                this["RealTime_VVVF_Hexagon_Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RealTime_Train_Hexagon_Style {
            get {
                return ((int)(this["RealTime_Train_Hexagon_Style"]));
            }
            set {
                this["RealTime_Train_Hexagon_Style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RealTime_VVVF_Hexagon_ZeroVector {
            get {
                return ((bool)(this["RealTime_VVVF_Hexagon_ZeroVector"]));
            }
            set {
                this["RealTime_VVVF_Hexagon_ZeroVector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RealTime_Train_Hexagon_ZeroVector {
            get {
                return ((bool)(this["RealTime_Train_Hexagon_ZeroVector"]));
            }
            set {
                this["RealTime_Train_Hexagon_ZeroVector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_VVVF_FFT_Show {
            get {
                return ((bool)(this["RealTime_VVVF_FFT_Show"]));
            }
            set {
                this["RealTime_VVVF_FFT_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_Train_FFT_Show {
            get {
                return ((bool)(this["RealTime_Train_FFT_Show"]));
            }
            set {
                this["RealTime_Train_FFT_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_Train_Control_Precise {
            get {
                return ((bool)(this["RealTime_Train_Control_Precise"]));
            }
            set {
                this["RealTime_Train_Control_Precise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_VVVF_Control_Precise {
            get {
                return ((bool)(this["RealTime_VVVF_Control_Precise"]));
            }
            set {
                this["RealTime_VVVF_Control_Precise"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_VVVF_FS_Show {
            get {
                return ((bool)(this["RealTime_VVVF_FS_Show"]));
            }
            set {
                this["RealTime_VVVF_FS_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_Train_FS_Show {
            get {
                return ((bool)(this["RealTime_Train_FS_Show"]));
            }
            set {
                this["RealTime_Train_FS_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double RealTime_Train_SoundVolume {
            get {
                return ((double)(this["RealTime_Train_SoundVolume"]));
            }
            set {
                this["RealTime_Train_SoundVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double RealTime_VVVF_SoundVolume {
            get {
                return ((double)(this["RealTime_VVVF_SoundVolume"]));
            }
            set {
                this["RealTime_VVVF_SoundVolume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public double RealTimeMasconFrequencyChangeRate {
            get {
                return ((double)(this["RealTimeMasconFrequencyChangeRate"]));
            }
            set {
                this["RealTimeMasconFrequencyChangeRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62")]
        public int RealTimeMasconAccelerateKey {
            get {
                return ((int)(this["RealTimeMasconAccelerateKey"]));
            }
            set {
                this["RealTimeMasconAccelerateKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("66")]
        public int RealTimeMasconBrakeKey {
            get {
                return ((int)(this["RealTimeMasconBrakeKey"]));
            }
            set {
                this["RealTimeMasconBrakeKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int RealTimeMasconNeutralKey {
            get {
                return ((int)(this["RealTimeMasconNeutralKey"]));
            }
            set {
                this["RealTimeMasconNeutralKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200000")]
        public int RealtimeVvvfSamplingFrequency {
            get {
                return ((int)(this["RealtimeVvvfSamplingFrequency"]));
            }
            set {
                this["RealtimeVvvfSamplingFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192000")]
        public int RealtimeTrainSamplingFrequency {
            get {
                return ((int)(this["RealtimeTrainSamplingFrequency"]));
            }
            set {
                this["RealtimeTrainSamplingFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64")]
        public int RealtimeVvvfCalculateDivision {
            get {
                return ((int)(this["RealtimeVvvfCalculateDivision"]));
            }
            set {
                this["RealtimeVvvfCalculateDivision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public int RealtimeTrainCalculateDivision {
            get {
                return ((int)(this["RealtimeTrainCalculateDivision"]));
            }
            set {
                this["RealtimeTrainCalculateDivision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Language {
            get {
                return ((int)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ColorTheme {
            get {
                return ((int)(this["ColorTheme"]));
            }
            set {
                this["ColorTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_VVVF_WaveForm_Phase_Show {
            get {
                return ((bool)(this["RealTime_VVVF_WaveForm_Phase_Show"]));
            }
            set {
                this["RealTime_VVVF_WaveForm_Phase_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RealTime_Train_WaveForm_Phase_Show {
            get {
                return ((bool)(this["RealTime_Train_WaveForm_Phase_Show"]));
            }
            set {
                this["RealTime_Train_WaveForm_Phase_Show"] = value;
            }
        }
    }
}
